### ISSUE TITLE
工具箱扩展加载问题

### ISSUE THREAD

**Issue by haolong114** [qianqianhaiou/JunkPuppet#10]
![图片1](https://github.com/qianqianhaiou/JunkPuppet/assets/148675366/44aaeb42-75aa-4aba-9cb2-87cf89670a99)
工具箱扩展未正确加载如何处理

**Comment by qianqianhaiou** [comment]
> ![图片1](https://private-user-images.githubusercontent.com/148675366/334140369-44aaeb42-75aa-4aba-9cb2-87cf89670a99.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODA3MjEsIm5iZiI6MTcyNTg4MDQyMSwicGF0aCI6Ii8xNDg2NzUzNjYvMzM0MTQwMzY5LTQ0YWFlYjQyLTc1YWEtNGFiYS05Y2IyLTg3Y2Y4OTY3MGE5OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwOVQxMTEzNDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hZjUyYjJhNzAzMDVkZWM4ZGU0NWVlODA3N2VjZGZlYTBhMTBjMTgyNTY4Njc3OWUwZmRjOGE4ZDFkMDRkYmIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.M6BLmoI_xBnxcdFgII4vwtCTk7MOrrF2IbIjh7xorP0) 工具箱扩展未正确加载如何处理

抱歉，我没有考虑到非全屏显示的问题，你可以先按F11全屏浏览器就可以看到了，后续会将工具箱的位置重新计算放置的。（同时建议你在全屏的模式下进行操作，以便获取更加精确的操作坐标点）

**Comment by qianqianhaiou** [comment]
在v0.0.8版本已得到修复
