### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by qianqianhaiou** [qianqianhaiou/JunkPuppet#8]
1. 通过JunkPuppet自动生成 埋点js

**Comment by qianqianhaiou** [comment]
'--start-maximized',                    // 页面最大化
      '--disable-gpu',                        // 禁用GPU加速
      '--disable-dev-shm-usage',              // 禁用共享内存
      '--disable-setuid-sandbox',             // 禁用沙盒模式
      '--no-first-run',                       // 不需要首次运行
      '--no-sandbox',                         // 无沙盒模式
      '--no-zygote',                          // 禁用子进程
      '--disable-infobars',                   // 禁用自动化提示栏
      '--disable-browser-side-navigation',    // 禁用自动化导航
      '--disable-features=site-per-process',  // 禁用单独进程

**Comment by honglianlisi** [comment]
大佬，可以加一个爬取数据导出文件的功能嘛？

**Comment by qianqianhaiou** [comment]
> 大佬，可以加一个爬取数据导出文件的功能嘛？

sorry，很久没管这个仓库了，等十月份有时间了搞

**Comment by qianqianhaiou** [comment]
数据导出已移入backlog
